name: Deployment Pipeline

on:
  push:
    branches:
      - main  # Set this to any branch from which you want to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Specify a Node.js version supported by Heroku

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
      env:
        CI: true

    - name: Login to Heroku
      run: heroku login -i

    - name: Deploy to Heroku
      run: |
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:refs/heads/main
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Heroku API key
        HEROKU_APP_NAME: your-heroku-app-name  # Your Heroku app name

